#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     irSensor,       sensorI2CCustom)
#pragma config(Sensor, S3,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorFlipper,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    pivotServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    grabberLeft,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    grabberRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    latchServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.h"
#include "4546_AutoChooser.h"
#include "JoystickDriver.c"

// since the gearing of the motors is weird, one full wheel spin is now approx. 187 for the encoder value!

task main()
{
	//PC = Parking Center
	//still have to find the IR values
	//userInput();
	//waitForStart();
		/*
		if(ir in front)
		{
			forward x inches
			drop balls
			turn 45 right
			go little forward
			turn 45 left
			go forward and get pole
		}
		if(it in pos 2(diag))
		{
			turn x deg
			forward x inches
			turn x deg
			forward x inches
			drop balls
			turn 45 right
			go little forward
			turn 45 left
			go forward and get pole
		}
		if(it is in pos 3(perp))
		{
			turn x deg
			forward x inches
			turn x deg
			forward x inches
			drop balls
			turn 45 right
			go little forward
			turn 45 left
			go forward and get pole
		}
	*/
}
