#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSensor,       sensorI2CCustom)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libraries.h"

task main()
{
	moveOffRamp((57*280)/(4*PI));  // Ramp is ~57 inches
	//move((15*280)/(4*PI)); //the rest of the way is ~15 inches
	turn(-1, (4.5*PI*280)/(4*PI)); //turn 90 degrees left
	//if the ir beacon is directly in front of the robot, move up next to the pole, face it, and move forward to knock it over.
	if(irSeeker(5)){
			move(1, (48*280)/(4*PI), 50);
			turn(1, (4.5*PI*280)/(4*PI));
			move(1, (12*280)/(4*PI), 50);
	}
}

/*
theoretical encoders
while(nMotorEncoder[motorFR] < 360*numberSpins)
{
motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 50;
}
motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 0;
nMotorEncoder[motorFR] = nMotorEncoder[motorBR] = nMotorEncoder[motorFL] = nMotorEncoder[motorBL] = 0;
*/
