#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     irSensor,       sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//the amount of times we want the wheel to spin is recorded here
int numberSpins = 6.28318531;
//is this enough to move us off the ramp?
task autoMovement()
{
	while(nMotorEncoder[motorFR] < 360*numberSpins)
	{
		motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 50;
	}
	motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 0;
	nMotorEncoder[motorFR] = nMotorEncoder[motorBR] = nMotorEncoder[motorFL] = nMotorEncoder[motorBL] = 0;
}

bool irFinder(int n){
	return(n == );
}
task main()
{

	//waitForStart(); // Wait for the beginning of autonomous phase.

	//resetting all encoder values is a must
	nMotorEncoder[motorFR] = nMotorEncoder[motorBR] = nMotorEncoder[motorFL] = nMotorEncoder[motorBL] = 0;

	startTask(autoMovement);
	/*
	RAMP-CENTER PSEUDOCODE
	numberSpins = x;
	while(nMotorEncoder[motorFR] < 360*x)
	{
	forward off the ramp
	motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 50;
	}
	motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 0;
	nMotorEncoder[motorFR] = nMotorEncoder[motorBR] = nMotorEncoder[motorFL] = nMotorEncoder[motorBL] = 0;

	numberSpins = x;
	while(nMotorEncoder[motorFR] < 360*x)
	{
	turning left
	motor[motorFR] = motor[motorBR] = 50;
	motor[motorFL] = motor[motorBL] = -50;
	}
	motor[motorFR] = motor[motorBR] = motor[motorFL] = motor[motorBL] = 0;
	nMotorEncoder[motorFR] = nMotorEncoder[motorBR] = nMotorEncoder[motorFL] = nMotorEncoder[motorBL] = 0;
	*/



}
