#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     irSensor,       sensorI2CCustom)
#pragma config(Sensor, S3,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorFlipper,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    pivotServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    grabberLeft,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    grabberRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    latchServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.h"
#include "4546_AutoChooser.h"
#include "JoystickDriver.c"

// since the gearing of the motors is weird, one full wheel spin is now approx. 187 for the encoder value!

task main()
{
	//RG = Ramp Goal
	//userInput();
	waitForStart();


	//arcturn param = power, deg, time
	//moveto param = power, encoder, time


	grabber(false);
	wait1Msec(50);

	adjustLift(500);

	moveTo(-35, -9999, 2500); // moves forward to get off the ramp
	wait1Msec(10);
	moveTo(-20, -500, 1000); //moves forward slower to not let goal roll away
	wait1Msec(10);
	grabber(true); //grabs the goal
	wait1Msec(50);
	//the following works very similar to getting out of a parking zone with a car
	//rotTurn(50, -150);
	arcTurn(50, 15);//turns a little
	moveTo(40, 500, 1000);// move forward a little
	arcTurn(50, 20); //turns a little

	rotTurn(50, 90);
	rotTurn(50, 90);
	//now it is moving backwards
	moveTo(-35, -1000, 5000); //goes to parking
	arcTurn(25, -35);
	moveTo(-35, -500, 1000);
	grabber(false);
	wait1Msec(50);
	moveTo(40, 1000, 2000);
	//1 = front, 2 = diag, 3 = perp
	if(getPositionPark() == 1)
	{
		arcTurn(50, 10);
		moveTo(50, 400, 1000);
		arcTurn(50, -10);
		moveTo(60, 1000, 2000);
	}
	if(getPositionPark() == 2)
	{
		arcTurn(50, -45);
		moveTo(50, 1000, 2000);
		rotTurn(50, 90);
		moveTo(50, 500, 1000);
	}
	if(getPositionPark() == 3)
	{
		arcTurn(50, -45);
		moveTo(50, 1500, 2000);
		rotTurn(50, 90);
		rotTurn(50, 45);
		moveTo(50, 500, 1000);
	}

	/*
	moveTo(30, 3500);
	arcTurn(50, 90);
	arcTurn(50, 90);
	grabber(false);
	wait1Msec(50);
	*/

	/*
	arcTurn(25, 180);
	lifter(999, 3000);
	grabber(false);
	arcTurn(25, 180);
	moveTo(-50, -1500);
	grabber(true);
	moveTo(50, 1500);
	arcTurn(25, 180);
	grabber(false);
	arcTurn(25, 180);
	moveTo(-50, -1500);
	grabber(true);
	moveTo(50, 1500);
	arcTurn(25, 180);
	grabber(false);
	*/
}
