#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorFlipper,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{

}

task tankDrive()
{
	while(true)
	{
		getJoystickSettings(joystick);
		short y1 = -joystick.joy1_y1;
		//Moving is done forward and backward with one joystick
		if(abs(joystick.joy1_y1) >= 15)
		{
			motor[motorFL] = y1 * .7;
			motor[motorBL] = y1 * .7;
			motor[motorFR] = y1 * .7;
	  	motor[motorBR] = y1 * .7;
		}

	  //LB
	  else if(joy1Btn(5) == 1)
	  {
	  	motor[motorFL] = 90;
			motor[motorBL] = 90;
			motor[motorFR] = -90;
	  	motor[motorBR] = -90;
	  }
	  //RB
	  else if(joy1Btn(6) == 1)
	  {
	  	motor[motorFL] = -90;
			motor[motorBL] = -90;
			motor[motorFR] = 90;
	  	motor[motorBR] = 90;
		}
	 	else
	 	{
	 		motor[motorFL] = 0;
			motor[motorBL] = 0;
			motor[motorFR] = 0;
			motor[motorBR] = 0;
		}
	}
}

//find what the gyro reads while going up the ramp
//set motors to different values when you found out what the rotation is
task onRamp()
{

}

task manipulation()
{
	//if x is pressed, flipper flips in
	if(joy2Btn(1) == 1)
	{
		motor[motorFlipper] = 100;
	}
	//if y is pressed, flipper flips out
	if(joy2Btn(2) == 1)
	{
		motor[motorFlipper] = -100;
	}
	else
	{
		motor[motorFlipper] = 0;
	}
}
task main()
{
	initializeRobot();

  waitForStart();   // wait for start of tele-op phase
  startTask(tankDrive);
  startTask(manipulation);
  while(true)
  {
	  wait1Msec(5);
  }
}
