#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     irSensorR,      sensorI2CCustom)
#pragma config(Sensor, S3,     irSensorL,      sensorI2CCustom)
#pragma config(Sensor, S4,     SENSOR_GYRO,    sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorFlipper,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libs.h"

task main()
{



	/*
	moveOffRamp((57*280)/(4*PI));  // Ramp is ~57 inches
	//move((15*280)/(4*PI)); //the rest of the way is ~15 inches
	turn(-1, (4.5*PI*280)/(4*PI)); //turn 90 degrees left
	//if the ir beacon is directly in front of the robot, move up next to the pole, face it, and move forward to knock it over.
	if(irSeeker(5)){
			move(1, (48*280)/(4*PI), 50);
			turn(1, (4.5*PI*280)/(4*PI));
			move(1, (12*280)/(4*PI), 50);
	}
	*/
}
/*
on ramp to mid
CURRENTLY JUST THEORETICAL
LOOK AT YELLOW PAGES TO SEE WHAT WE WANT TO DO
moveOffRamp(encoder);
turnGyro(-90);
move(1, encoder, 50);
//aka opponent IR in front
if(irSeeker(5) || whatever)
{
	turnGyro(-45);
	move(1, encoder, 50);
	turnGyro(45);
	move(1, encoder, 50);
	turnGyro(135);
	irSeekerStuff;
	move(1, encoder, 50);
	dropBalls;
	turnGyro(90);
	move(1, encoder, 50);
	turnGyro(-90);
	move(1, econder, 50);
}
//aka opponent IR not exact front
else
{
	turnGyro(45);
	if(ir certain value)
	{
		while(ir isnt a certain value)
		{
			startMotors(50, -50);
		}
	}

}
*/
