#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     irSensor,       sensorI2CCustom)
#pragma config(Sensor, S3,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorFlipper,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    pivotServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    grabberLeft,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    grabberRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    latchServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.h"
#include "4546_AutoChooser.h"
#include "JoystickDriver.c"

// since the gearing of the motors is weird, one full wheel spin is now approx. 187 for the encoder value!

task main()
{
	//RC = Ramp Center
	//userInput();
	//waitForStart();
	adjustLift(500);
	moveTo(25, 2000, 1000);
	arcTurn(50, -90);
	moveTo(50, 1000, 1000);
	//aka directly in front pos 1
	if(getPositionRamp() == 1)
	{
		arcTurn(50, -10);
		moveTo(50, 730, 1000);
		arcTurn(50, 10);
		moveTo(60, 1000, 2000);
	}
	//if(irPosition is in pos 2 (diag))
	if(getPositionRamp() == 2)
	{
		arcTurn(50, -30);
		moveTo(60, 1000, 2000);
	}
	//if(irPosition is in pos 3(perpendicular))
	if(getPositionRamp() == 3)
	{
		arcTurn(50, -45);
		moveTo(50, 730, 1000);
		rotTurn(50, 90);
		rotTurn(50, 45);
		moveTo(60, 1000, 2000);
	}

	//all pseudocode was moved to a separate txt file on desktop, it is named comments
}
