#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorLifterR,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorUnused,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorLifterL,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorSpinner,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C3_1,    dropperL,             tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    dropperR,             tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

//the robot lifts the balls here
task manipulation()
{
	while(true)
	{
		getJoystickSettings(joystick);
		//lb lifts the slides up
		if(joy2Btn(5) == 1)
		{
			//make sure that the motors work correctly before testing
			motor[motorLifterR] = 20;
			motor[motorLifterL] = -20;
		}
		//rb lowers the slides
		else if(joy2Btn(6) == 1)
		{
			//make sure that the motors work correctly before testing
			motor[motorLifterR] = -20;
			motor[motorLifterL] = 20;
		}
		//lt makes the spinner pull the balls in
		else if(joy2Btn(7) == 1)
		{
			motor[motorSpinner] = -90;
		}
		//rt makes the spinner go the opposite way
		else if(joy2Btn(8) == 1)
		{
			motor[motorSpinner] = 90;
		}
		else
		{
			motor[motorLifterR] = motor[motorLifterL] = motor[motorSpinner] = 0;
		}
			//B button drop the balls
		if(joy2Btn(3) == 1)
		{
		servo[dropperL] = 0; //enter "open" position here
		servo[dropperR] = 150; //enter "open" position here
		}

		//A button makes sure that balls don't fall out
		if(joy2Btn(2) == 1)
		{
		servo[dropperL] = 150; //enter "closed" position here
		servo[dropperR] = 0; //enter "closed" position here
		}
	}
}

//basic mecanum drive code
task mecanumDrive()
{
	//setting the initial values for the use by the joysticks
	short x1 = 0;
	short y1 = 0;
	short x2 = 0;
	//start of basic drive code
	while(true)
	{
		//threshhold is currently set to 15, please set lower if you need the joystick to be more responsive
		getJoystickSettings(joystick); //must getJoystick, otherwise the values will not be received
		if(abs(joystick.joy1_x1) > 15)
		{
			x1 = joystick.joy1_x1;
		}
		else
		{
			x1 = 0;
		}

		if(abs(joystick.joy1_y1) > 15)
		{
			y1 = -joystick.joy1_y1;
		}
		else
		{
			y1 = 0;
		}

		if(abs(joystick.joy1_x2) > 15)
		{
			x2 = joystick.joy1_x2;
		}
		else
		{
			x2 = 0;
		}

		//set variables for the motors
		short fl = y1 + x2 + x1;
		short bl = y1 + x2 - x1;
		short fr = y1 - x2 - x1;
		short br = y1 - x2 + x1;

		//make sure that the values cannot exceed 100 on the motors, if it doesn't, set the values to their regular formula values
		if(fl > 100){
			motor[motorFL] = 100;
		}
		else if(fl < -100){
			motor[motorFL] = -100;
		}
		else{
			motor[motorFL] = fl;
		}
		if(bl > 100){
			motor[motorBL] = 100;
		}
		else if(bl < -100){
			motor[motorBL] = -100;
		}
		else{
			motor[motorBL] = bl;
		}
		if(fr > 100){
			motor[motorFR] = 100;
		}
		else if(fr < -100){
			motor[motorFR] = -100;
		}
		else{
			motor[motorFR] = fr;
		}
		if(br > 100){
			motor[motorBR] = 100;
		}
		else if(br < -100){
			motor[motorBR] = -100;
		}
		else{
			motor[motorBR] = br;
		}
	}
}

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	startTask(mecanumDrive);
	startTask(manipulation);

	while (true)
	{
		wait1Msec(5);
	}
}
