#pragma config(Sensor, S3,     irSensorL,      sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h";
#include "hitechnic-irseeker-v2.h"

//float gyro = 0;
//int rightIR = 0;
int leftIR = 0;
//int frEncoder = 0;
//int flEncoder = 0;
string leftIRVal = "";
task main()
{
	wait1Msec(500);
	//HTGYROstartCal(SENSOR_GYRO);
	wait1Msec(500);
	while(true)
	{
		//gyro = HTGYROreadRot(SENSOR_GYRO);
		//rightIR = HTIRS2readACDir(irSensorR);
		leftIR = HTIRS2readACDir(irSensorL);
		//frEncoder = nMotorEncoder[motorFR];
		//flEncoder = nMotorEncoder[motorFL];
	}
}
